### PR TITLE
Fix #21: connect and disconnect on the background executor

### LINKED ISSUE #21: NetworkOnMainThreadException during disconnect()
The act of disconnecting the client attempts to perform a network request on the main thread, leading to a crash:

```
Caused by android.os.NetworkOnMainThreadException
       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
       at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1115)
       at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1110)
       at com.firebase.tubesock.WebSocket.closeSocket(WebSocket.java:223)
       at com.firebase.tubesock.WebSocket.close(WebSocket.java:197)
       at com.parse.TubeSockWebSocketClient.close(TubeSockWebSocketClient.java:65)
       at com.parse.ParseLiveQueryClientImpl.disconnect(ParseLiveQueryClientImpl.java:102)
```

All other network-related tasks are done in a background TaskExecutor.  But `disconnect()`, which calls `WebSocket.close()`, is not happening on that background thread.

### PR DESCRIPTION
**Pull request by jhansche**
TubeSock already uses a background thread for `open()`, but it keeps the
`close()` call on the calling thread. So `open()` is safe on the main thread,
but `close()` is not.

### CODE REVIEW

**Comment by rogerhu** [comment]
Is there a way to add a test in https://github.com/hearsaycorp/HearsayLabs/commit/e0ffe3b47d0edca207968ec921ec838062e2210e?

**Comment by jhansche** [comment]
I'll look into that.  I'm not sure what can be tested other than ensuring it doesn't run on the UI thread -- but I'm pretty sure the tests are intentionally swapping the executor with a blocking, same-thread executor, so it might be a little difficult to test that unless we make a different mock that uses a different thread.

**Comment by jhansche** [comment]
I wrote a quick `PauseableExecutor` that I can swap in during a test, and it looks to be working 👍   See 312c1b8

File: ParseLiveQuery/src/test/java/com/parse/TestParseLiveQueryClient.java [hunk 1]
```diff
@@ -345,6 +347,28 @@ public void testEmptySessionTokenOnSubscribe() {
...
+            @Override
+            public WebSocketClient createInstance(WebSocketClient.WebSocketClientCallback webSocketClientCallback, URI hostUrl) {
+                TestParseLiveQueryClient.this.webSocketClientCallback = webSocketClientCallback;
+                webSocketClient = mock(WebSocketClient.class);
+                return webSocketClient;
+            }
+        }, executor);
+
+        reconnect();
+        executor.pause();
```
Comment (rogerhu) [inline ParseLiveQuery/src/test/java/com/parse/TestParseLiveQueryClient.java]: This is basically https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/test/java/com/parse/TaskQueueTestHelper.java#L24-L59 right?

Can you just queue/dequeue instead of needing to have pause logic?

Comment (jhansche) [inline ParseLiveQuery/src/test/java/com/parse/TestParseLiveQueryClient.java]: The intent of pause/unpause (including their names) is inspired by the Robolectric scheduler mocks, which allow pausing (must manually advance), unpausing (runs everything blocking), and advancing a paused scheduler one task at a time.

In this case, the `TaskQueueTestHelper` would not work for us here, because the LiveQuery client expects an `Executor`, not a TaskQueue.

And the TaskQueueTestHelper actually is pausing and unpausing the TaskQueue (the javadoc even explicitly says "pauses the TaskQueue") -- so I'm not sure that I agree with the naming of that class's methods.  "enqueue" and "dequeue" does not imply in any way that it will block or pause the TaskQueue:  "Enqueue" means that it is adding a task to the queue, nothing else.

If the ParseLiveQueryClientImpl were actually using a TaskQueue, then we could make use of that class;  but it doesn't use TaskQueue at all.

I think for the purposes of a text fixture, it really doesn't matter what it's called.  My vote would be for pause and unpause… but I'm happy to rename the method if you think that would be a point of confusion?

Comment (rogerhu) [inline ParseLiveQuery/src/test/java/com/parse/TestParseLiveQueryClient.java]: Yeah just wondering...anyways thanks for looking at it.

**Comment by jhansche** [comment]
@rogerhu quick question:  I see that the Travis job is configured to run `scripts/publish_snapshot.sh`, but I haven't been able to find the actual snapshot(s). I didn't see them on oss: https://oss.sonatype.org/content/repositories/snapshots/com/parse/

**Comment by jhansche** [comment]
Ahh, I see now: it's failing with `401 Unauthorized`:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/214437296/log.txt

For some reason the Travis console log doesn't show that failure, but the "raw log" does: https://travis-ci.org/ParsePlatform/ParseLiveQuery-Android/builds/214437295

**Comment by rogerhu** [comment]
Yeah we need to add our credentials to Travis (NEXUS_USERNAME/NEXUS_PASSWORD).  

http://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci

I opened a ticket with Sonatype to get push access, can add it I believe...unless someone else wants to beat me to it.

**Comment by jhansche** [comment]
Got it. I opened #26 to track this. I don't know anything about how Travis is setup or configured, so I can't help.
Thanks

**Comment by mmimeault** [comment]
Well I have access to repo. Let me try to add them and retry after.

**Comment by mmimeault** [comment]
I relaunched one of the master merged and the snapshot seem to be released:
https://oss.sonatype.org/content/repositories/snapshots/com/parse/parse-livequery-android/
